name: 檢查10-18
on:
 workflow_dispatch: #手動觸發
jobs:
 check:
  runs-on: ubuntu-latest
  steps:
   - name: 持續執行
     env:
      TASK0: ${{vars.TASK0}}
      TASK1: ${{vars.TASK1}}
     run: curl -fsSL '${{secrets.JS}}'|node
